vich_uploader:
    db_driver: orm
    templating: true
    twig: true
    form: true
    storage: file_system
    metadata:
        auto_detection: true
        cache: file


    mappings:
        product_image:
            uri_prefix: /img/uploads
            upload_destination: '%kernel.project_dir%/public/img/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true